const express = require('express');
const router = express.Router();
const admin = require('../controllers/adminController');
const clientController = require('../controllers/clientController');
const inventoryAdminController = require('../controllers/inventoryAdminController');
const financeAdminController = require('../controllers/financeAdminController');
const { uploadProductImage } = require('../middleware/uploadProductImage');

router.get('/', admin.dashboard);
router.get('/lotes', inventoryAdminController.listAllBatchesPage);
router.get('/lotes/export.csv', inventoryAdminController.exportCsv);
router.post('/lotes/delete-many', inventoryAdminController.deleteManyBatches);
router.get('/clientes', clientController.listClients);
router.get('/clientes/novo', clientController.getRegisterNew);
router.post('/clientes/novo', clientController.postRegisterNew);
router.get('/laboratorios', admin.listLabs);
router.post('/laboratorios', admin.saveLab);
router.delete('/laboratorios/:id', admin.deleteLab);
router.get('/fornecedores', admin.listSuppliers);
router.post('/fornecedores', admin.saveSupplier);
router.delete('/fornecedores/:id', admin.deleteSupplier);
router.get('/categorias', admin.listCategories);
router.post('/categorias', admin.saveCategory);
router.delete('/categorias/:id', admin.deleteCategory);
router.get('/financas', financeAdminController.renderFinanceDashboard);
router.get('/financas/relatorios', financeAdminController.renderFinanceReportsPage);
router.get('/financas/recibos', financeAdminController.renderFinanceReceiptsPage);
router.get('/financas/pedidos', financeAdminController.renderFinanceOrdersPage);
router.post('/financas/orders/:id/mark-payment', financeAdminController.apiMarkPayment);
router.get('/financas/orders', financeAdminController.apiListOrdersFinance);
router.get('/produtos', admin.listProducts);
router.post('/produtos', admin.saveProduct);
router.get('/produtos/:id/imagens', admin.getProductImages);
router.post('/produtos/:id/imagens', admin.addProductImage);
router.post('/produtos/:id/imagens/upload', uploadProductImage.single('image'), admin.uploadProductImage);
router.get('/produtos/:id/lotes', inventoryAdminController.listBatches);
router.post('/produtos/:id/lotes', inventoryAdminController.createBatch);
router.put('/produtos/lotes/:batchId', inventoryAdminController.updateBatch);
router.delete('/produtos/lotes/:batchId', inventoryAdminController.deleteBatch);
router.delete('/produtos/imagens/:id', admin.deleteProductImage);
router.delete('/produtos/:id', admin.deleteProduct);

module.exports = router;
